# Generated by Django 5.1.6 on 2025-02-17 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='check-in date')),
                ('check_out_date', models.DateField(verbose_name='check-out date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked in'), ('CHECKED_OUT', 'Checked out'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=11, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total price')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='beds.bed', verbose_name='bed')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='guests.guest', verbose_name='guest')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'indexes': [models.Index(fields=['bed', 'check_in_date', 'check_out_date'], name='bookings_bo_bed_id_12c4b3_idx'), models.Index(fields=['status'], name='bookings_bo_status_233e96_idx')],
            },
        ),
    ]
