# Generated by Django 5.1.6 on 2025-03-23 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('guests', '0002_alter_guest_options_alter_guest_birth_date_and_more'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_bed_id_12c4b3_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='bed',
        ),
        migrations.AddField(
            model_name='booking',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.unit', verbose_name='Unidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(verbose_name='Fecha de entrada'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(verbose_name='Fecha de salida'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='guests.guest', verbose_name='Huésped'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('CHECKED_IN', 'Registrado'), ('CHECKED_OUT', 'Salida'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=11, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio total'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['unit', 'check_in_date', 'check_out_date'], name='bookings_bo_unit_id_42da8c_idx'),
        ),
    ]
