# Generated by Django 5.1.6 on 2025-03-23 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'Huésped', 'verbose_name_plural': 'Huéspedes'},
        ),
        migrations.AlterField(
            model_name='guest',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='document_number',
            field=models.CharField(max_length=20, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='document_type',
            field=models.CharField(choices=[('DNI', 'Documento Nacional de Identidad'), ('PASSPORT', 'Pasaporte')], max_length=8, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='nationality',
            field=models.CharField(max_length=50, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Número de teléfono'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='reservation_owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propietario de la reserva'),
        ),
    ]
