# Generated by Django 5.1.6 on 2025-03-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_cashregister_cashregisterentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashregisterentry',
            name='cash_register',
        ),
        migrations.DeleteModel(
            name='CashRegister',
        ),
    ]
