FROM nginx:1.23-alpine

RUN apk --update add tzdata && \
    cp /usr/share/zoneinfo/America/Argentina/Mendoza /etc/localtime && \
    echo "America/Argentina/Mendoza" > /etc/timezone && \
    apk del tzdata

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d