# Generated by Django 5.1.6 on 2025-02-14 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Room name should be unique', max_length=50, verbose_name='name')),
                ('room_type', models.CharField(choices=[('DORM', 'Dormitory'), ('PRIVATE', 'Private Room')], max_length=7, verbose_name='room type')),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='base price')),
                ('capacity', models.IntegerField(blank=True, default=1, verbose_name='capacity')),
                ('description', models.TextField(blank=True, help_text='Room description (private bathroom, amenities, etc.', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='number')),
                ('bed_type', models.CharField(choices=[('SINGLE', 'Single Bed'), ('BUNK_TOP', 'Top Bunk'), ('BUNK_BOTTOM', 'Bottom Bunk'), ('DOUBLE', 'Double Bed')], default='SINGLE', max_length=11, verbose_name='bed type')),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='base price')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='beds.room', verbose_name='room')),
            ],
            options={
                'verbose_name': 'bed',
                'verbose_name_plural': 'beds',
                'unique_together': {('room', 'number')},
            },
        ),
    ]
