# Generated by Django 5.1.6 on 2025-02-17 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='base_price',
        ),
    ]
