# Generated by Django 5.1.6 on 2025-02-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0002_remove_room_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(
                help_text='Room name should be unique',
                max_length=50,
                unique=True,
                verbose_name='name'
                ),
        ),
    ]
