# Generated by Django 5.1.6 on 2025-05-05 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_unit_unit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='El nombre de la propiedad debe ser único.', max_length=128, unique=True, verbose_name='Nombre')),
                ('property_type', models.CharField(choices=[('HOTEL', 'Hotel'), ('HOSTEL', 'Hostal/Albergue'), ('CAMPING', 'Camping'), ('RESORT', 'Resort/Complejo turístico'), ('APARTMENT', 'Hotel apartamento/Apart-hotel'), ('BNB', 'Bed and Breakfast'), ('GUESTHOUSE', 'Casa de huéspedes'), ('BOUTIQUE', 'Hotel boutique'), ('ECOLODGE', 'Eco-lodge/Alojamiento ecológico'), ('VACATION_RENTAL', 'Alquiler vacacional'), ('GLAMPING', 'Glamping'), ('OTHER', 'Otro tipo de alojamiento')], max_length=32, verbose_name='Tipo de propiedad')),
                ('description', models.TextField(blank=True, help_text='Descripción general de la propiedad', verbose_name='Descripción')),
                ('address', models.TextField(blank=True, help_text='Dirección física de la propiedad', verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='El nombre de la habitación debe ser único dentro de la propiedad.', max_length=128, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='room',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.property', verbose_name='Propiedad'),
            preserve_default=False,
        ),
    ]
