# Generated by Django 5.1.6 on 2025-05-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_property_alter_room_name_room_property'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('property', 'name')},
        ),
    ]
