FROM python:3.13-slim

RUN apt-get update && \
	apt-get install libpq-dev gcc build-essential libssl-dev libffi-dev -y

ENV TZ = America/Argentina/Mendoza

WORKDIR /home/public

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

EXPOSE 8000

# Dependencias
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt